/**
 * ops SECDEF RPC 의 P0001 RAISE 접두사 → AppError 매핑 (EmployerApplicationRepository.mapRpcError 패턴).
 * 알려지지 않은 에러는 handleSupabaseError 로 폴백(전송/일반 분류).
 */
import { BusinessError, ERROR_CODES } from '@/errors';
import { handleSupabaseError } from '@/utils/supabase';

interface RpcErrorLike {
  message?: string;
  code?: string;
}

const PREFIX_MAP: readonly (readonly [string, string, string])[] = [
  ['REGISTRATION_CLOSED', ERROR_CODES.OPS_REGISTRATION_CLOSED, ERROR_CODES.OPS_REGISTRATION_CLOSED],
  [
    'INVALID_STATUS',
    ERROR_CODES.OPS_INVALID_TOURNAMENT_TRANSITION,
    ERROR_CODES.OPS_INVALID_TOURNAMENT_TRANSITION,
  ],
  // 좌석/테이블 — 더 구체적인 접두사 우선 (부분일치 방지)
  [
    'SEAT_VERSION_CONFLICT',
    ERROR_CODES.OPS_SEAT_VERSION_CONFLICT,
    ERROR_CODES.OPS_SEAT_VERSION_CONFLICT,
  ],
  ['SEAT_TAKEN', ERROR_CODES.OPS_SEAT_TAKEN, ERROR_CODES.OPS_SEAT_TAKEN],
  ['SEAT_NOT_OCCUPIED', ERROR_CODES.OPS_SEAT_NOT_OCCUPIED, ERROR_CODES.OPS_SEAT_NOT_OCCUPIED],
  ['SEAT_NOT_FOUND', ERROR_CODES.OPS_SEAT_NOT_OCCUPIED, ERROR_CODES.OPS_SEAT_NOT_OCCUPIED],
  ['TABLE_HAS_OCCUPANTS', ERROR_CODES.OPS_TABLE_HAS_OCCUPANTS, ERROR_CODES.OPS_TABLE_HAS_OCCUPANTS],
  ['TABLE_NOT_FOUND', ERROR_CODES.OPS_TABLE_NOT_FOUND, ERROR_CODES.OPS_TABLE_NOT_FOUND],
  ['TABLE_NOT_OPEN', ERROR_CODES.OPS_TABLE_NOT_OPEN, ERROR_CODES.OPS_TABLE_NOT_OPEN],
  // 입력 검증 — INVALID_STATUS/INVALID_MOVE 와 상호 부분문자열 아님(순서 무관)
  ['INVALID_SEAT_COUNT', ERROR_CODES.OPS_INVALID_SEAT_COUNT, ERROR_CODES.OPS_INVALID_SEAT_COUNT],
  ['INVALID_ASSIGNMENTS', ERROR_CODES.OPS_INVALID_ASSIGNMENTS, ERROR_CODES.OPS_INVALID_ASSIGNMENTS],
  // 블라인드/클럭 (1c) — RPC 가 'OPS_*' 전체 토큰으로 RAISE → 기존 INVALID_* 접두사와 비충돌
  [
    'OPS_BLIND_LEVELS_INVALID',
    ERROR_CODES.OPS_BLIND_LEVELS_INVALID,
    ERROR_CODES.OPS_BLIND_LEVELS_INVALID,
  ],
  ['OPS_NO_BLIND_LEVELS', ERROR_CODES.OPS_NO_BLIND_LEVELS, ERROR_CODES.OPS_NO_BLIND_LEVELS],
  ['OPS_INVALID_LEVEL', ERROR_CODES.OPS_INVALID_LEVEL, ERROR_CODES.OPS_INVALID_LEVEL],
  // 모니터(1c-3) — 공개 토큰 무효. ⚠️ OPS_MONITOR_CONFIG_INVALID 와 접두사 비충돌(TOKEN vs CONFIG)
  [
    'OPS_MONITOR_TOKEN_INVALID',
    ERROR_CODES.OPS_MONITOR_TOKEN_INVALID,
    ERROR_CODES.OPS_MONITOR_TOKEN_INVALID,
  ],
  // 전면 개방 S1 — 모니터 구성(C6)·상금 지급(C4)·공개뷰 신고(B2)
  [
    'OPS_MONITOR_CONFIG_INVALID',
    ERROR_CODES.OPS_MONITOR_CONFIG_INVALID,
    ERROR_CODES.OPS_MONITOR_CONFIG_INVALID,
  ],
  [
    'OPS_PRIZE_NOT_ASSIGNED',
    ERROR_CODES.OPS_PRIZE_NOT_ASSIGNED,
    ERROR_CODES.OPS_PRIZE_NOT_ASSIGNED,
  ],
  [
    'OPS_PRIZE_PAID_INVALID',
    ERROR_CODES.OPS_PRIZE_NOT_ASSIGNED,
    ERROR_CODES.OPS_PRIZE_NOT_ASSIGNED,
  ],
  [
    'OPS_REPORT_TOKEN_INVALID',
    ERROR_CODES.OPS_REPORT_TOKEN_INVALID,
    ERROR_CODES.OPS_REPORT_TOKEN_INVALID,
  ],
  [
    'OPS_REPORT_RATE_LIMITED',
    ERROR_CODES.OPS_REPORT_RATE_LIMITED,
    ERROR_CODES.OPS_REPORT_RATE_LIMITED,
  ],
  // 플레이어뷰(claim 분리) — ALREADY_CLAIMED·PIN_INVALID·VIEW_TOKEN_INVALID (상호 부분문자열 아님)
  [
    'OPS_CLAIM_ALREADY_CLAIMED',
    ERROR_CODES.OPS_CLAIM_ALREADY_CLAIMED,
    ERROR_CODES.OPS_CLAIM_ALREADY_CLAIMED,
  ],
  ['OPS_CLAIM_PIN_INVALID', ERROR_CODES.OPS_CLAIM_PIN_INVALID, ERROR_CODES.OPS_CLAIM_PIN_INVALID],
  [
    'OPS_VIEW_TOKEN_INVALID',
    ERROR_CODES.OPS_VIEW_TOKEN_INVALID,
    ERROR_CODES.OPS_VIEW_TOKEN_INVALID,
  ],
  // 참가자 — bust/reentry/ITM (1d)
  [
    'PARTICIPANT_ALREADY_BUSTED',
    ERROR_CODES.OPS_PARTICIPANT_ALREADY_BUSTED,
    ERROR_CODES.OPS_PARTICIPANT_ALREADY_BUSTED,
  ],
  [
    'PARTICIPANT_NOT_BUSTED',
    ERROR_CODES.OPS_PARTICIPANT_NOT_BUSTED,
    ERROR_CODES.OPS_PARTICIPANT_NOT_BUSTED,
  ],
  [
    'PARTICIPANT_LAST_SURVIVOR',
    ERROR_CODES.OPS_PARTICIPANT_LAST_SURVIVOR,
    ERROR_CODES.OPS_PARTICIPANT_LAST_SURVIVOR,
  ],
  ['REENTRY_NOT_ALLOWED', ERROR_CODES.OPS_REENTRY_NOT_ALLOWED, ERROR_CODES.OPS_REENTRY_NOT_ALLOWED],
  [
    'MAX_REENTRIES_EXCEEDED',
    ERROR_CODES.OPS_MAX_REENTRIES_EXCEEDED,
    ERROR_CODES.OPS_MAX_REENTRIES_EXCEEDED,
  ],
  [
    'PRIZE_STRUCTURE_INVALID',
    ERROR_CODES.OPS_PRIZE_STRUCTURE_INVALID,
    ERROR_CODES.OPS_PRIZE_STRUCTURE_INVALID,
  ],
  // 배정 2종 — SEAT_ASSIGNMENT_INVALID·INVALID_REDRAW_MODE (기존 SEAT_*/INVALID_* 와 상호 부분문자열 아님)
  [
    'SEAT_ASSIGNMENT_INVALID',
    ERROR_CODES.OPS_SEAT_ASSIGNMENT_INVALID,
    ERROR_CODES.OPS_SEAT_ASSIGNMENT_INVALID,
  ],
  ['INVALID_REDRAW_MODE', ERROR_CODES.OPS_INVALID_REDRAW_MODE, ERROR_CODES.OPS_INVALID_REDRAW_MODE],
  // 참가자 — PARTICIPANT_ALREADY_SEATED 를 NOT_* 앞에
  [
    'PARTICIPANT_ALREADY_SEATED',
    ERROR_CODES.OPS_PARTICIPANT_ALREADY_SEATED,
    ERROR_CODES.OPS_PARTICIPANT_ALREADY_SEATED,
  ],
  [
    'PARTICIPANT_NOT_ACTIVE',
    ERROR_CODES.OPS_PARTICIPANT_NOT_ACTIVE,
    ERROR_CODES.OPS_PARTICIPANT_NOT_ACTIVE,
  ],
  [
    'PARTICIPANT_NOT_FOUND',
    ERROR_CODES.OPS_PARTICIPANT_NOT_FOUND,
    ERROR_CODES.OPS_PARTICIPANT_NOT_FOUND,
  ],
  [
    'TOURNAMENT_NOT_FOUND',
    ERROR_CODES.OPS_TOURNAMENT_NOT_FOUND,
    ERROR_CODES.OPS_TOURNAMENT_NOT_FOUND,
  ],
  // 1f — 넉아웃/탈락취소/상금정정. 각 접두사는 상호·기존과 부분문자열 아님
  // (PRIZE_CORRECTION_INVALID ≠ PRIZE_STRUCTURE_INVALID, UNDO_INVALID_STATE ≠ INVALID_STATUS).
  ['ELIMINATOR_INVALID', ERROR_CODES.OPS_ELIMINATOR_INVALID, ERROR_CODES.OPS_ELIMINATOR_INVALID],
  ['UNDO_INVALID_STATE', ERROR_CODES.OPS_UNDO_INVALID_STATE, ERROR_CODES.OPS_UNDO_INVALID_STATE],
  [
    'PRIZE_CORRECTION_INVALID',
    ERROR_CODES.OPS_PRIZE_CORRECTION_INVALID,
    ERROR_CODES.OPS_PRIZE_CORRECTION_INVALID,
  ],
  ['INVALID_MOVE', ERROR_CODES.BUSINESS_INVALID_STATE, ERROR_CODES.BUSINESS_INVALID_STATE],
  // 1e — 스태프 로스터/공고연결. TABLE_NOT_FOUND 는 기존 매핑 재사용(위 SEAT/TABLE 블록), 재추가 금지.
  ['NO_LINKED_POSTING', ERROR_CODES.BUSINESS_INVALID_STATE, ERROR_CODES.BUSINESS_INVALID_STATE],
  ['DUPLICATE_STAFF', ERROR_CODES.BUSINESS_INVALID_STATE, ERROR_CODES.BUSINESS_INVALID_STATE],
  ['STAFF_NOT_IN_ROSTER', ERROR_CODES.BUSINESS_INVALID_STATE, ERROR_CODES.BUSINESS_INVALID_STATE],
  ['STAFF_NOT_FOUND', ERROR_CODES.INFRA_NOT_FOUND, ERROR_CODES.INFRA_NOT_FOUND],
  // POSTING_NOT_FOUND 누락 시 handleSupabaseError 폴백으로 원시 에러 노출(보안 게이트 메시지 유실) — 필수 매핑.
  ['POSTING_NOT_FOUND', ERROR_CODES.INFRA_NOT_FOUND, ERROR_CODES.INFRA_NOT_FOUND],
];

export function mapOpsRpcError(error: unknown, ctx: { operation: string }): never {
  const message = (error as RpcErrorLike)?.message ?? '';

  for (const [prefix, code] of PREFIX_MAP) {
    if (message.includes(prefix)) {
      // userMessage 는 ERROR_MESSAGES[code] (한글) 가 자동 적용됨.
      throw new BusinessError(code);
    }
  }

  if (message.includes('PERMISSION_DENIED')) {
    throw new BusinessError(ERROR_CODES.BUSINESS_INVALID_STATE, {
      userMessage: '이 작업을 수행할 권한이 없습니다',
    });
  }

  // 알 수 없는 에러(전송/제약 등) → 표준 핸들러로 분류.
  handleSupabaseError(error, { operation: ctx.operation, table: 'ops' });
}
