export const EXPO_ROUTES = {
  root: '/',

  home: '/(app)/(tabs)',
  schedule: '/(app)/(tabs)/schedule',
  profile: '/(app)/(tabs)/profile',
  employerTab: '/(app)/(tabs)/employer',
  qr: '/(app)/(tabs)/qr',

  notifications: '/(app)/notifications',
  jobDetail: '/(app)/jobs/[id]',
  jobApply: '/(app)/jobs/[id]/apply',
  settings: '/(app)/settings',
  settingsProfile: '/(app)/settings/profile',
  settingsChangePassword: '/(app)/settings/change-password',
  settingsDeleteAccount: '/(app)/settings/delete-account',
  settingsPrivacy: '/(app)/settings/privacy',
  settingsTerms: '/(app)/settings/terms',
  settingsEmployerTerms: '/(app)/settings/employer-terms',
  settingsLiabilityWaiver: '/(app)/settings/liability-waiver',
  settingsMyData: '/(app)/settings/my-data',
  settingsBusinessInfo: '/(app)/settings/business-info',
  applicationCancel: '/(app)/applications/[id]/cancel',
  employerRegister: '/(app)/employer-register',

  notices: '/(app)/notices',
  noticeDetail: '/(app)/notices/[id]',

  support: '/(app)/support',
  supportFaq: '/(app)/support/faq',
  supportCreateInquiry: '/(app)/support/create-inquiry',
  supportMyInquiries: '/(app)/support/my-inquiries',
  supportInquiryDetail: '/(app)/support/inquiry/[id]',

  myPostings: '/(employer)/my-postings',
  postingCreate: '/(employer)/my-postings/create',
  postingDetail: '/(employer)/my-postings/[id]',
  postingEdit: '/(employer)/my-postings/[id]/edit',
  postingApplicants: '/(employer)/my-postings/[id]/applicants',
  postingSettlements: '/(employer)/my-postings/[id]/settlements',
  postingCancellationRequests: '/(employer)/my-postings/[id]/cancellation-requests',

  adminDashboard: '/(admin)',
  adminUsers: '/(admin)/users',
  adminUserDetail: '/(admin)/users/[id]',
  adminStats: '/(admin)/stats',
  adminReports: '/(admin)/reports',
  adminReportDetail: '/(admin)/reports/[id]',
  adminAnnouncements: '/(admin)/announcements',
  adminAnnouncementCreate: '/(admin)/announcements/create',
  adminAnnouncementDetail: '/(admin)/announcements/[id]',
  adminAnnouncementEdit: '/(admin)/announcements/[id]/edit',
  adminTournaments: '/(admin)/tournaments',
  adminInquiries: '/(admin)/inquiries',
  adminInquiryDetail: '/(admin)/inquiries/[id]',

  reviewDetail: '/(app)/reviews/[workLogId]',
  reviewsPending: '/(app)/reviews/pending',

  publicJobs: '/(public)/jobs',
  publicJobDetail: '/jobs/[id]',

  login: '/(auth)/login',
  signup: '/(auth)/signup',
  forgotPassword: '/(auth)/forgot-password',
} as const;

export type ExpoRouteName = keyof typeof EXPO_ROUTES;
export type ExpoRoutePath = (typeof EXPO_ROUTES)[ExpoRouteName];

export const AUTH_REQUIRED_ROUTES: ExpoRouteName[] = [
  'home',
  'notifications',
  'schedule',
  'profile',
  'settings',
  'settingsProfile',
  'settingsChangePassword',
  'settingsDeleteAccount',
  'settingsPrivacy',
  'settingsTerms',
  'settingsEmployerTerms',
  'settingsLiabilityWaiver',
  'settingsMyData',
  'settingsBusinessInfo',
  'support',
  'supportFaq',
  'supportCreateInquiry',
  'supportMyInquiries',
  'supportInquiryDetail',
  'notices',
  'noticeDetail',
  'jobApply',
  'applicationCancel',
  'employerRegister',
  'myPostings',
  'postingCreate',
  'postingDetail',
  'postingEdit',
  'postingApplicants',
  'postingSettlements',
  'postingCancellationRequests',
  'reviewDetail',
  'reviewsPending',
];

export const EMPLOYER_REQUIRED_ROUTES: ExpoRouteName[] = [
  'myPostings',
  'postingCreate',
  'postingDetail',
  'postingEdit',
  'postingApplicants',
  'postingSettlements',
  'postingCancellationRequests',
];

export const ADMIN_REQUIRED_ROUTES: ExpoRouteName[] = [
  'adminDashboard',
  'adminUsers',
  'adminUserDetail',
  'adminStats',
  'adminReports',
  'adminReportDetail',
  'adminAnnouncements',
  'adminAnnouncementCreate',
  'adminAnnouncementDetail',
  'adminAnnouncementEdit',
  'adminTournaments',
  'adminInquiries',
  'adminInquiryDetail',
];
