export const EXPO_ROUTES = {
  root: '/',

  home: '/(app)/(tabs)/home-jobs',
  schedule: '/(app)/(tabs)/schedule',
  board: '/(app)/(tabs)/board',
  profile: '/(app)/(tabs)/profile',
  employerTab: '/(app)/(tabs)/employer',
  qr: '/(app)/(tabs)/qr',

  notifications: '/(app)/notifications',
  jobDetail: '/(app)/jobs/[id]',
  jobApply: '/(app)/jobs/[id]/apply',
  settings: '/(app)/settings',
  settingsProfile: '/(app)/settings/profile',
  settingsChangePassword: '/(app)/settings/change-password',
  settingsDeleteAccount: '/(app)/settings/delete-account',
  settingsPrivacy: '/(app)/settings/privacy',
  settingsTerms: '/(app)/settings/terms',
  settingsEmployerTerms: '/(app)/settings/employer-terms',
  settingsLiabilityWaiver: '/(app)/settings/liability-waiver',
  settingsMyData: '/(app)/settings/my-data',
  settingsBusinessInfo: '/(app)/settings/business-info',
  applicationCancel: '/(app)/applications/[id]/cancel',
  employerRegister: '/(app)/employer-register',

  notices: '/(app)/(tabs)/board/notice',
  noticeDetail: '/(app)/(tabs)/board/post/[postId]',

  support: '/(app)/support',
  supportFaq: '/(app)/support/faq',
  supportCreateInquiry: '/(app)/support/create-inquiry',
  supportMyInquiries: '/(app)/support/my-inquiries',
  supportInquiryDetail: '/(app)/support/inquiry/[id]',

  postingCreate: '/(employer)/my-postings/create',
  postingDetail: '/(employer)/my-postings/[id]',
  postingEdit: '/(employer)/my-postings/[id]/edit',
  postingApplicants: '/(employer)/my-postings/[id]/applicants',
  postingSettlements: '/(employer)/my-postings/[id]/settlements',
  postingCancellationRequests: '/(employer)/my-postings/[id]/cancellation-requests',
  weeklyGrid: '/(employer)/weekly-grid',

  adminDashboard: '/(admin)',
  adminUsers: '/(admin)/users',
  adminUserDetail: '/(admin)/users/[id]',
  adminStats: '/(admin)/stats',
  adminReports: '/(admin)/reports',
  adminReportDetail: '/(admin)/reports/[id]',
  adminBoardReports: '/(admin)/board-reports',
  adminBoardReportDetail: '/(admin)/board-reports/[id]',
  adminAnnouncements: '/(admin)/announcements',
  adminAnnouncementCreate: '/(admin)/announcements/create',
  adminAnnouncementDetail: '/(admin)/announcements/[id]',
  adminAnnouncementEdit: '/(admin)/announcements/[id]/edit',
  adminTournaments: '/(admin)/tournaments',
  adminInquiries: '/(admin)/inquiries',
  adminInquiryDetail: '/(admin)/inquiries/[id]',
  adminEmployerApplications: '/(admin)/employer-applications',
  adminEmployerApplicationDetail: '/(admin)/employer-applications/[id]',

  employerApplicationStatus: '/(app)/employer-application-status',

  reviewDetail: '/(app)/reviews/[workLogId]',
  reviewsPending: '/(app)/reviews/pending',

  // 워크스페이스 협업 (PR #2)
  workspace: '/(employer)/workspace',
  workspaceInvite: '/(employer)/workspace/invite',
  workspaceInvitations: '/(employer)/workspace/invitations',

  publicJobs: '/(public)/jobs',
  publicJobDetail: '/jobs/[id]',

  login: '/(auth)/login',
  signup: '/(auth)/signup',
  forgotPassword: '/(auth)/forgot-password',
} as const;

export type ExpoRouteName = keyof typeof EXPO_ROUTES;
export type ExpoRoutePath = (typeof EXPO_ROUTES)[ExpoRouteName];

export const AUTH_REQUIRED_ROUTES: ExpoRouteName[] = [
  'home',
  'notifications',
  'schedule',
  'board',
  'profile',
  'settings',
  'settingsProfile',
  'settingsChangePassword',
  'settingsDeleteAccount',
  'settingsPrivacy',
  'settingsTerms',
  'settingsEmployerTerms',
  'settingsLiabilityWaiver',
  'settingsMyData',
  'settingsBusinessInfo',
  'support',
  'supportFaq',
  'supportCreateInquiry',
  'supportMyInquiries',
  'supportInquiryDetail',
  'notices',
  'noticeDetail',
  'jobApply',
  'applicationCancel',
  'employerRegister',
  'postingCreate',
  'postingDetail',
  'postingEdit',
  'postingApplicants',
  'postingSettlements',
  'postingCancellationRequests',
  'weeklyGrid',
  'reviewDetail',
  'reviewsPending',
  'employerApplicationStatus',
  // 워크스페이스 협업 (PR #2)
  'workspace',
  'workspaceInvite',
  'workspaceInvitations',
];

export const EMPLOYER_REQUIRED_ROUTES: ExpoRouteName[] = [
  'postingCreate',
  'postingDetail',
  'postingEdit',
  'postingApplicants',
  'postingSettlements',
  'postingCancellationRequests',
  'weeklyGrid',
];

export const ADMIN_REQUIRED_ROUTES: ExpoRouteName[] = [
  'adminDashboard',
  'adminUsers',
  'adminUserDetail',
  'adminStats',
  'adminReports',
  'adminReportDetail',
  'adminBoardReports',
  'adminBoardReportDetail',
  'adminAnnouncements',
  'adminAnnouncementCreate',
  'adminAnnouncementDetail',
  'adminAnnouncementEdit',
  'adminTournaments',
  'adminInquiries',
  'adminInquiryDetail',
  'adminEmployerApplications',
  'adminEmployerApplicationDetail',
];
